### PR TITLE
If shop has higher amounts than a stack, use the shop amount to allow…

### PR DESCRIPTION
**Pull request by AlexanderMoebius**
… players to use bulk discount

### CODE REVIEW

**Comment by Flowsqy** [comment]
I'm in holidays, and I don't have my computer for 3 weeks so I will probably answer lately. Also, I can't write code.
Anyway, listeners (and particulary this one) are very messy and unclear, so they need to be fully rewritten. I will probably leave this here until I get back home. 
In any cases, thx for the work :D

**Comment by AlexanderMoebius** [comment]
Will you merge these changes?

**Comment by Flowsqy** [comment]
I started a review to understand some details about one or two things. (If you can't see it, then my bad, it's my first review x) )
But nobody asked for it and I'm working (as much as I can alongside my studies) on the transaction process, rewritting everything. So I will not keep it at the end. If you are the only one that need that, I prefere to keep it open like that and close it when it will be implemented in the new code. You can use it with your own version for the moment ^^'. The next release of ShopChest will have it but writted not this way.

**Comment by AlexanderMoebius** [comment]
I thought you could just merge it and then change the whole code.
So you also probably won't miss this feature

**Pull request merged**
