### PR TITLE
Update item_names.txt

### PR DESCRIPTION
**Pull request by mrfloris**
to rename SCUTE for 1.21.1 TURTLE_SCUTE

### CODE REVIEW

**Comment by mrfloris** [comment]
It might be worth considering to review what's missing besides the error I got ; 
https://www.diffchecker.com/ulx9y9eG/

**Comment by mrfloris** [comment]
Oh, sorry, back again

```
[17:27:36 INFO]: mrfloris issued server command: /shops create 1 1 1 admin
[17:27:37 ERROR]: [ShopChest] Could not get the translation for 'item.minecraft.turtle_scute'. Report it to github
>
```
forgot about that, ugh.

**Comment by Flowsqy** [comment]
First to solve your issue: you need to update items names as specified in the README with LangGenerator. 
Then, I don't even know what item_names.txt is used for and the idiot who rewrote the whole language system (me) probably just forgot to delete the file x). (because after a quick look at the code, it's not used anywhere).
I will clean this later.

**Comment by mrfloris** [comment]
> First to solve your issue: you need to update items names as specified in the README with LangGenerator. Then, I don't even know what item_names.txt is used for and the idiot who rewrote the whole language system (me) probably just forgot to delete the file x). (because after a quick look at the code, it's not used anywhere). I will clean this later.

Thank you for the information, sorry for the noob issue.

**Comment by Flowsqy** [comment]
No problem :D

**Pull request closed without merging**
